# Generated by Django 2.0.4 on 2018-06-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNum',
            fields=[
                ('licenseplate', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('phoneNum', models.CharField(max_length=11)),
                ('province', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=12)),
                ('carnum', models.CharField(default='0', max_length=8)),
                ('author', models.CharField(default='无', max_length=10)),
                ('remark', models.CharField(default='无', max_length=40)),
                ('createDate', models.DateTimeField(default='2018-06-06 22:00:01', null=True)),
            ],
        ),
    ]
