# Generated by Django 2.0.4 on 2018-04-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('license', models.CharField(max_length=5)),
                ('licenseplate', models.CharField(max_length=10)),
                ('phonenum', models.CharField(max_length=11)),
                ('carnum', models.CharField(max_length=30)),
                ('startdate', models.DateField()),
            ],
        ),
    ]
