# Generated by Django 2.0.4 on 2018-04-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlateManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseplate',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
