# Generated by Django 2.0.4 on 2018-06-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlateManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenum',
            name='city',
            field=models.CharField(default='无', max_length=12),
        ),
        migrations.AlterField(
            model_name='phonenum',
            name='createDate',
            field=models.DateTimeField(default='2018-06-06 23:22:31', null=True),
        ),
        migrations.AlterField(
            model_name='phonenum',
            name='phoneNum',
            field=models.CharField(default='无', max_length=11),
        ),
        migrations.AlterField(
            model_name='phonenum',
            name='province',
            field=models.CharField(default='无', max_length=12),
        ),
    ]
