# Generated by Django 2.0.5 on 2018-05-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlateManage', '0003_phonenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenum',
            name='carnum',
            field=models.CharField(default='0', max_length=8),
        ),
        migrations.AddField(
            model_name='phonenum',
            name='remark',
            field=models.CharField(default='无', max_length=40),
        ),
    ]
