# Generated by Django 2.0.5 on 2018-05-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlateManage', '0004_auto_20180522_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenum',
            name='license',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='phonenum',
            name='createDate',
            field=models.DateTimeField(null=True),
        ),
    ]
