# Generated by Django 2.0.5 on 2018-05-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlateManage', '0005_auto_20180522_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenum',
            name='author',
            field=models.CharField(default='无', max_length=10),
        ),
        migrations.AddField(
            model_name='phonenum',
            name='licenseplate',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='phonenum',
            name='createDate',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
