# Generated by Django 2.0.4 on 2018-05-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlateManage', '0006_auto_20180522_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenum',
            name='licenseplate',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
